### ISSUE TITLE
Breaking changes from v5.0.3 to v6.0.0?

### ISSUE THREAD

**Issue by philmorley** [spotify-api/spotify-api.js#17]
Getting these errors when compiling TS using spotify-api.js

```zsh
src/spotify.ts:41:20 - error TS2554: Expected 2 arguments, but got 0.
const user = new Spotify.UserClient();
                      ~~~~~~~~~~~~~~~~~~

node_modules/spotify-api.js/dist/UserClient.d.ts:50:17
constructor(token: string | undefined, client: Client);
                                       ~~~~~~~~~~~~~~~~
An argument for 'token' was not provided.

src/spotify.ts:80:22 - error TS2554: Expected 2 arguments, but got 1.
const userPlayer = new Spotify.UserPlayer(token);
                                 ~~~~~~~~~~~~~~~~

node_modules/spotify-api.js/dist/UserPlayer.d.ts:11:28
constructor(data: any, client: Client);
                       ~~~~~~~~~~~~~
An argument for 'client' was not provided.

src/spotify.ts:86:16 - error TS2554: Expected 2 arguments, but got 1.
const user = new Spotify.UserClient(token);
                      ~~~~~~~~~~~~~~~~~~~~~~

node_modules/spotify-api.js/dist/UserClient.d.ts:50:44
constructor(token: string | undefined, client: Client);
                                          ~~~~~~~~~~
An argument for 'client' was not provided.
```

## My version of spotify-api.js
Version 6.0.0

## What i expected...
These errors are new since the update from v5.0.3 to v6.0.0. I'm not seeing any arguments that match "client: Client" in the docs here -> https://spotify-api-js-test.netlify.app/#/class/userplayer

## But what happened is...
Getting an error stating that there are missing arguments for Spotify.UserClient & Spotify.UserPlayer. The docs do not address these arguments.

**Comment by Scientific-Guy** [comment]
See first v6 is buggy as i said in the readme but tbh it works fine but you have made a mistake over there<br/>
You dont need initiate the `UserClient` class seperately you can do something like this:

```js
const client = new Spotify.Client("TOKEN");
const userclient = client.user;
const userplayer = client.user.player;
```

This will work fine, if any errors report and docs is outdated. The docs ur viewing is of v5 and old one!
@abh80 is on leave, so he is not updating the docs. Docs is ready but, it will release it v7!

**Comment by philmorley** [comment]
Thanks for the response. The readme states that v5 is buggy not v6! 

I'll keep an eye open for updates. 

Thanks for all of your work.

**Comment by abh80** [comment]
Planning to publish v7 tomorrow after testing

**Comment by abh80** [comment]
Ok @philmorley V7 is now released on npm so make sure to check it out

**Comment by Scientific-Guy** [comment]
@philmorley v7 has published update it!

**Comment by abh80** [comment]
Open this issue again if you have any issue regarding this package and if the issue still persists.
